### ISSUE TITLE
大神 ！请问该如何配置，我填完4个appid和secret后一直报空指针

### ISSUE THREAD

**Issue by zoudongping** [zh417233956/keycloak-services-social-dingtalk#1]
03:07:01,700 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-5) Uncaught server error: java.lang.NullPointerException
keycloak    |   at org.keycloak.keycloak-server-spi-private@11.0.0//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1922)
keycloak    |   at org.keycloak.keycloak-services@11.0.0//org.keycloak.services.resources.admin.IdentityProvidersResource.create(IdentityProvidersResource.java:192)
keycloak    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak    |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak    |   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak    |   at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)

**Comment by zoudongping** [comment]
是不是配置有问题 
Dingtalk Login Appid 
Dingtalk Login Secret 
Dingtalk App Appid 
Dingtalk App Secret 
  这4个分别怎么配呀

**Comment by zh417233956** [comment]
Login Appid和Login Secret分别对应扫码登录应用授权中的appId和appSecret，用于登录换取用户的unionid
App Appid和App Secret则是应用授权的key和secret，用来换取token获取用户信息

**Comment by zh417233956** [comment]
> 是不是配置有问题
> Dingtalk Login Appid
> Dingtalk Login Secret
> Dingtalk App Appid
> Dingtalk App Secret
> 这4个分别怎么配呀

Login Appid和Login Secret分别对应扫码登录应用授权中的appId和appSecret，用于登录换取用户的unionid
App Appid和App Secret则是应用授权的key和secret，用来换取token获取用户信息

**Comment by zh417233956** [comment]
> > 是不是配置有问题
> > Dingtalk Login Appid
> > Dingtalk Login Secret
> > Dingtalk App Appid
> > Dingtalk App Secret
> > 这4个分别怎么配呀
> 
> Login Appid和Login Secret分别对应扫码登录应用授权中的appId和appSecret，用于登录换取用户的unionid
> App Appid和App Secret则是应用授权的key和secret，用来换取token获取用户信息

你需要确保你的扫码应用回调地址正确，并且钉钉应用中的服务器出口IP配置正确

**Comment by zh417233956** [comment]
App Appid和App Secre或者Dingtalk UserInfo Url 二选一，
Dingtalk UserInfo Url：可以用来调用内部的api获取用户信息，get接口
url配置：http://xxx.xxx.xx/api/xxx/xxx
回调参数：action=get_userid_by_unionid&unionid=xxxxx
返回结构：`{
"errcode": 0,
"dduserid": "xxxxxx",
"contactType": "0",
"name": "xxx",
"jobnumber": "xxx"
}`
